---
- name: Create Inventory Dinamic
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    temp_inventory: myhosts
    hosts_list:
      - node1.lab.example.com
      - node2.lab.example.com
  tasks:    
    - name: Getting new hosts
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: "{{ temp_inventory }}"
      loop: "{{ hosts_list }}"

- name: Create Inventory Dinamic
  hosts: myhosts
  gather_facts: no
  vars:
    - satellite_url: "https://satellite.lw76p.sandbox2012.opentlc.com/"
    - satellite_org: "Default Organization"
    - satellite_ak_rhel8: "RHEL8_DEV"
      
  tasks:
        
    - name: Install Katello CA RPM from Satellite
      ansible.builtin.dnf:
        name: "{{ satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
        state: present
        sslverify: false
        validate_certs: false
        disable_gpg_check: true
  
    - name: Register RHEL8 server on Satellite
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ satellite_ak_rhel8 }}"
        org_id: "{{ satellite_org }}"
        force_register: true
     
    
    
    #==================================================================
    
    # This needs to run on a host with API access
    #- name: "Generate registration command"
    #  redhat.satellite.registration_command:
    #    username: "admin"
    #    password: "changeme"
    #    server_url: "https://satellite.example.com"
    #  register: command
    #  delegate_to: localhost
    
    # This needs to run on the host being registered
    #- name: "Perform registration"
    #  ansible.builtin.shell:
    #    cmd: "{{ command.registration_command }}"
    
    #========================================================
    #- name: Set a hostgroup on new host registered
    #  redhat.satellite.host:
    #      username: "{{ satellite_user }}"
    #      password: "{{ satellite_pass }}"
    #      server_url: "{{ satellite_url }}"
    #      name: "{{ inventory_hostname }}"
    #      organization: "{{ satellite_org }}"
    #     hostgroup: "JOAO"
    #      validate_certs: falses
